name: Surf
version: 3.3.2
main: org.surf.Main
authors: [ 254n_m, Leeewith3Es, Dreeam ]
description:  ${project.description}
website: https://breeze.asia
api-version: 1.13
softdepend: [ NBTAPI ]
commands:
  surf:
    description: The main command of Surf.