name: ${name}
version: ${version}
main: cn.dreeam.surf.Surf
description: ${description}
api-version: 1.13
folia-supported: true

softdepend:
  - NBTAPI
authors:
  - 254n_m
  - Leeewith3Es
  - Dreeam-qwq
  - Loyisa
commands:
  surf:
    description: The main command of Surf.
permissions:
  surf.command.main:
    description: The main command of Surf.
    default: op
  surf.bypass.chunkban:
    default: op
  surf.bypass.netherroof:
    default: op
