name: EN | Bug report
description: Create a report to help us improve
labels: ["bug"]

body:
  - type: markdown
    attributes:
      value: |
        Before reporting an issue, make sure you tried latest dev build of Surf and checked for duplicate issues in [Issues](https://github.com/Winds-Studio/Surf/issues)!

  - type: checkboxes
    attributes:
      label: Checklist
      description: |
        Before you scroll down, select boxes below.
      options:
        - label: I have searched the existing issues
          required: true
        - label: I ticked all the boxes without actually reading them
          required: false
        - label: I am using latest dev build from https://github.com/Winds-Studio/Surf/releases
          required: true

  - type: textarea
    attributes:
      label: What behaviour is observed?
      description: A clear and concise description of what the behavior is.
    validations:
      required: true

  - type: textarea
    attributes:
      label: Expected behaviour
      description: A clear and concise description of what you expected to happen.
    validations:
      required: true

  - type: textarea
    attributes:
      label: To Reproduce
      description: Steps to reproduce this behaviour
      placeholder: |
        1. Enter server '...'
        2. execute command /example '...'
        3. Server crashes '...'
        4. See error
    validations:
      required: true

  - type: input
    attributes:
      label: Spark profiler link
      description: |
        Link of spark profiler, which including helpful information helps us to work with your issue,
        see https://spark.lucko.me/docs/ to learn how to use spark.
    validations:
      required: true

  - type: input
    attributes:
      label: Error log (if applicable)
      description: If you are reporting a console error, upload any relevant errors or full log to either https://mclo.gs or https://gist.github.com, save and the paste the link in this box.

  - type: input
    attributes:
      label: Surf configuration (if applicable)
      description: If your issue related to configuration, upload all of your Surf configurations to either https://mclo.gs or https://gist.github.com, save and the paste the link in this box.
